# Generated by Django 4.0.8 on 2023-01-30 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=256)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosdem.box')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosdem.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='boxes',
            field=models.ManyToManyField(through='fosdem.Transport', to='fosdem.box'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_have', models.IntegerField()),
                ('have', models.IntegerField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosdem.box')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosdem.item')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='items',
            field=models.ManyToManyField(through='fosdem.Inventory', to='fosdem.item'),
        ),
    ]
